WITH TOTAL_VENDAS(ANO, MES, VENDAS) AS
(
	SELECT
		DATEPART(YEAR, S.DateKey) AS ANO
		,DATEPART(MONTH, S.DateKey) AS MES
		,SUM(S.SalesAmount) AS VENDAS
	FROM ContosoRetailDW.dbo.FactOnlineSales AS S
	GROUP BY DATEPART(YEAR, S.DateKey), DATEPART(MONTH, S.DateKey)
)
SELECT
	ANO 
	,MES 
	,FORMAT(VENDAS, 'C0') AS 'VENDAS'
	,FORMAT(SUM(VENDAS) OVER(), 'C0') AS 'VENDAS_TOTAL'
	,FORMAT(SUM(VENDAS) OVER(PARTITION BY ANO), 'C0') AS 'VENDAS_TOTAL_ANO'
	,FORMAT(SUM(VENDAS) OVER(PARTITION BY ANO  ORDER BY MES), 'C0') AS 'VENDAS_YTD'
FROM TOTAL_VENDAS
ORDER BY ANO, MES