WITH TOTAL_VENDAS(ANO, MES, VENDAS) AS
(
	SELECT
		DATEPART(YEAR, S.DateKey) AS ANO
		,DATEPART(MONTH, S.DateKey) AS MES
		,SUM(S.SalesAmount) AS VENDAS
	FROM ContosoRetailDW.dbo.FactOnlineSales AS S
	GROUP BY DATEPART(YEAR, S.DateKey), DATEPART(MONTH, S.DateKey)
)
SELECT
	ANO 
	,MES 
	,FORMAT(VENDAS, 'C0') AS 'VENDAS'
	,FORMAT(SUM(VENDAS) OVER(ORDER BY ANO, MES ASC
						ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING), 'C0') AS 'VENDAS_MES_ANTERIOR'
	,FORMAT(SUM(VENDAS) OVER(ORDER BY ANO, MES ASC
						ROWS BETWEEN 2 PRECEDING AND 1 PRECEDING), 'C0') AS 'VENDAS_2_MESES_ANTERIORES'
	,FORMAT(SUM(VENDAS) OVER(ORDER BY ANO, MES ASC
						ROWS BETWEEN 0 PRECEDING AND 0 PRECEDING), 'C0') AS 'VENDAS_MES_ATUAL'
	,VENDAS-SUM(VENDAS) OVER(ORDER BY ANO, MES ASC
						ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS 'FLUXO_DO_MES'
FROM TOTAL_VENDAS
ORDER BY ANO, MES