WITH TOTAL_VENDAS(ANO, MES, VENDAS) AS
(
	SELECT
		DATEPART(YEAR, S.DateKey) AS ANO
		,DATEPART(MONTH, S.DateKey) AS MES
		,SUM(S.SalesAmount) AS VENDAS
	FROM ContosoRetailDW.dbo.FactOnlineSales AS S
	GROUP BY DATEPART(YEAR, S.DateKey), DATEPART(MONTH, S.DateKey)
)
SELECT
	ANO 
	,MES 
	,FORMAT(VENDAS, 'C0') AS 'VENDAS'
	,FORMAT(LAG(VENDAS, 1, 0) OVER(ORDER BY ANO, MES ASC), 'C0') AS 'MES_ANTERIOR'
	,FORMAT(LEAD(VENDAS, 1, 0) OVER(ORDER BY ANO, MES ASC), 'C0') AS 'MES_POSTERIOR'
-- LAG(VENDAS, "Numero de linhas a pular", "se não encontrar, o numero que vai mostrar")
FROM TOTAL_VENDAS
ORDER BY ANO, MES